version: '3.4'

services:
  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile

  fooddelivery:
    image: ${DOCKER_REGISTRY-}fooddelivery
    build:
      context: .
      dockerfile: FoodDelivery/Dockerfile

  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile
      
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "12345"
    ports:
        - "1433:1433"