version: '3.4'

services:
  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile

  fooddelivery:
    image: ${DOCKER_REGISTRY-}fooddelivery
    build:
      context: .
      dockerfile: FoodDelivery/Dockerfile

  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile




